"""add generation_jobs, generation_runs, asset_scores, event_log

Revision ID: 5566ad86f45c
Revises: 2aa62647e5cc
Create Date: 2026-04-16 19:10:08.606819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5566ad86f45c'
down_revision: Union[str, Sequence[str], None] = '2aa62647e5cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('subject_type', sa.String(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('actor', sa.String(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_log_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_log_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_log_id'), ['id'], unique=False)
        batch_op.create_index('ix_event_log_subject', ['subject_type', 'subject_id'], unique=False)

    op.create_table('asset_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('aesthetic', sa.Float(), nullable=True),
    sa.Column('persona_consistency', sa.Float(), nullable=True),
    sa.Column('prompt_adherence', sa.Float(), nullable=True),
    sa.Column('artifact_penalty', sa.Float(), nullable=True),
    sa.Column('novelty', sa.Float(), nullable=True),
    sa.Column('overall', sa.Float(), nullable=True),
    sa.Column('verdict', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('model_used', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('asset_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asset_scores_content_id'), ['content_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_scores_id'), ['id'], unique=False)

    op.create_table('generation_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('persona_id', sa.Integer(), nullable=True),
    sa.Column('job_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('content_id', sa.Integer(), nullable=True),
    sa.Column('campaign_task_id', sa.Integer(), nullable=True),
    sa.Column('machine', sa.String(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], ),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('generation_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_generation_jobs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_generation_jobs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_generation_jobs_status'), ['status'], unique=False)

    op.create_table('generation_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('refined_prompt', sa.Text(), nullable=True),
    sa.Column('negative_prompt', sa.Text(), nullable=True),
    sa.Column('loras', sa.JSON(), nullable=True),
    sa.Column('backend', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('seed', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('machine', sa.String(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('output_path', sa.String(), nullable=True),
    sa.Column('preview_path', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['generation_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('generation_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_generation_runs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_generation_runs_job_id'), ['job_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generation_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_generation_runs_job_id'))
        batch_op.drop_index(batch_op.f('ix_generation_runs_id'))

    op.drop_table('generation_runs')
    with op.batch_alter_table('generation_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_generation_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_generation_jobs_id'))
        batch_op.drop_index(batch_op.f('ix_generation_jobs_created_at'))

    op.drop_table('generation_jobs')
    with op.batch_alter_table('asset_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asset_scores_id'))
        batch_op.drop_index(batch_op.f('ix_asset_scores_content_id'))

    op.drop_table('asset_scores')
    with op.batch_alter_table('event_log', schema=None) as batch_op:
        batch_op.drop_index('ix_event_log_subject')
        batch_op.drop_index(batch_op.f('ix_event_log_id'))
        batch_op.drop_index(batch_op.f('ix_event_log_event_type'))
        batch_op.drop_index(batch_op.f('ix_event_log_created_at'))

    op.drop_table('event_log')
    # ### end Alembic commands ###
